[package]
name = "edgeless_utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
rand = "0.8"
uuid = "0.8"
tokio = { version = "1", features = ["full"] }